site_name: BHR Docker Guide
theme: readthedocs
docs_dir: docs
markdown_extensions:
  - admonition
nav:
  - 'BHR': index.md
  - 'Installing Docker': docker_install.md
  - 'Installing BHR': bhr_install.md
  - 'Rest API Specification': rest_api.md